# Generated by Django 3.2 on 2022-05-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='plate',
            new_name='code',
        ),
    ]
