# Generated by Django 3.2 on 2022-05-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_rename_plate_books_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='code',
            new_name='plate',
        ),
    ]
